---
- hosts: localhost

  vars:
    
  tasks:
    - debug:
        msg: "Running PLAYBOOK SSH Configure"

    - name: Same as above but subscribe to a specific pool by ID.
      redhat_subscription:
        state: present
        username: "{{ rhn_user }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ rhn_pool }}"

