---
- hosts: all
  gather_facts: false
  connection: local
  user: remote
  sudo: false

  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter vcenter hostname"
      private: no
      default: "192.168.1.26"
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
      default: "administrator@home.net"
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      default: "Smartvm!23"
      private: no

  vars:
    datacenter: 'Kenley'
    esxi_host: '192.168.1.21'
    notes: 'Created by Ansible'

  tasks:
    - vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_extra_config:
          notes: "{{ notes }}"
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network }}"
            network_type: standard
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: "{{ osid }}"
          scsi: paravirtual
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
