---
- hosts: all
  gather_facts: false
  remote_user: root
  
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
    
    - name: Copy File
      copy: src=/etc/hostname dest=/tmp/hostname.txt
