---

- hosts: localhost

  vars:
    miq_server: "192.168.1.64"
    create_user_name: 'fisherprice'
    create_user_password: 'secret'
    miq_user: 'admin'
    miq_pass: 'smartvm'
    miq_url1: "https://{{ miq_server }}/api/groups?expand=resources&attributes=description,href,id&filter[]=description='EvmGroup-user'"
    miq_url2: "https://{{ miq_server }}/api/users"

  tasks:
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=manageiq.event_target
    - name: Call to CloudForms to find href for EvmGroup-user
      uri:
        url: "{{ miq_url1 }}"
        method: GET
        validate_certs: no
        user: '{{ miq_user }}'
        password: '{{ miq_pass }}'
        force_basic_auth: yes
        body_format: json
        return_content: yes
      register: token_output

    - set_fact: group_id="{{ token_output.json.resources[0].id }}"

    - name: Call to ManageIQ to find href for EvmGroup-user
      uri:
        url: "{{ miq_url2 }}"
        method: POST
        validate_certs: no
        user: '{{ miq_user }}'
        password: '{{ miq_pass }}'
        force_basic_auth: yes
        HEADER_Content-Type: "application/json"
        body_format: json
        body: 
          userid: '{{ create_user_name }}'
          password: '{{ create_user_password }}'
          name: '{{ create_user_name }}'
          group: 
             id: '{{ group_id }}'
        return_content: yes
      register: token_output

    - debug: var=token_output.json


 