---

- hosts: localhost

  vars:
    miq_server: "192.168.1.90"
    create_user_name: 'fisherprice'
    create_user_password: 'secret'
    user_url: "{{ manageiq.api_url }}/api/users?expand=resources&attributes=name,href,id&filter[]=name='fisherprice'"

  tasks:
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=manageiq.event_target
    - name: Call to ManageIQ to find href for user fisherprice
      uri:
        url: "{{ user_url }}"
        method: GET
        validate_certs: no
        headers:
           X-Auth-Token: "{{ manageiq.api_token }}"
           Content-Type: "application/json"
        body_format: json
        return_content: yes
      register: token_output

    - set_fact: user_href="{{ token_output.json.resources[0].href }}"

    - name: Call to ManageIQ to delete the user fisherprice by href
      uri:
        url: "{{ user_href }}"
        method: POST
        validate_certs: no
        user: '{{ miq_user }}'
        password: '{{ miq_pass }}'
        force_basic_auth: yes
        HEADER_Content-Type: "application/json"
        body_format: json
        body: 
          action: 'delete'
        return_content: yes
      register: token_output

    - debug: var=token_output.json


